debezium/debezium-incubator

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java
https://issues.jboss.org/browse/DBZ-720
@jpechane This adjusts the `SnapshotDatatypesIT` so to actually test the (data) snapshotting. I think with that we can consider DBZ-720 as complete (unless you still see anything missing).
=> DBZ-720 Adjusting snapshotting test

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/Module.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/Module.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SourceInfoTest.java
This will allow consumers to recognize the Debezium connector used for creating a given message, helping them to adjust their behavior for a variety of connectors.
https://issues.jboss.org/browse/DBZ-918
=> DBZ-918 Adding Debezium connector field to source info

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
The entire initial snapshot process is executed in snapshot transaction
isolation level.
=> DBZ-941 Add "snapshot" snapshot locking mode

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDatabaseSchema.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
Adjusting test for database property pass-through, as the connection isn't established any longer synchronously within start().
=> DBZ-776 Removing redundant method;

debezium-connector-cassandra/pom.xml, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTask.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/network/SslConfig.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/network/SslContextFactory.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/CassandraConnectorConfigTest.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/EmbeddedCassandraConnectorTestBase.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/SnapshotProcessorTest.java
Use Property file instead of Yaml file for Cassandra Connector Config to get rid of SnakeYaml dependency.
=> [DBZ-1406] Replace Yaml Dependency With Property file.

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
@gunnarmorling There is a core API compatibility break
=> DBZ-1555 TableId parts precedence is configurable

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
Fix attempting to retrieve an SCN for all last_ddl_times, instead get most recent ddl_time and the SCN for that. Functionally equivalent, but won't fail when there's no snapshots for old ddls (on a pre-existing db for example)
=> DBZ-1631 - alter select to perform timestamp_to_scn on most recent

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, debezium-connector-db2/src/test/java/io/debezium/connector/db2/Db2ConnectorIT.java
This pull request addresses:
- Use only DB2 compatible isolation modes when taking Snapshots
- Remove some unused variables
=> DBZ-1752 DB2 connector follow-up tasks

README.md
Fixes the link to CONTRIBUTE.md in debezium-incubator repository README.md
https://issues.redhat.com/browse/DBZ-1795
=> DBZ-1795 Fix link to CONTRIBUTE.md

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogProcessor.java
Cassandra Connector shouldn't remove commitLog files under testing mode (`latest.commit.log.only=true`).
Added a condition check to only enqueue EOF (end-of-file) event when not under testing mode, so that QueueProcess won't poll and process a corresponding EOF event to move the commitLog file to relocation directory.
=> [DBZ-1927] Do not remove processed commitLog files under testing mode.

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/TransactionMetadataIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
The oracle integration tests use a number of Thread.sleep() calls to wait for
the snapshotting phase to finish before testing streaming changes but sometimes
this can be unreliable, especially on a slow running db. Instead of sleeping,
polling the jmx metrics to watch for when the snapshot phase ends is preferable.
=> Oracle connector integration tests poll jmx

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/AbstractDirectoryWatcher.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogProcessor.java
Tested and verified that the PR fixes the following critical bug:
Cassandra Connector only processed the first commitLogFile flushed into cdc_raw after the connector gets started/restarted, and wasn't able to process the follow-up ones flushed in.
- Reset watch key every time after handling the polled events.
- Add more logs for debugging.
=> [DBZ-1985] Fix Cassandra Connector stops processing new commitLogFiles in cdc_raw

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/KafkaRecordEmitter.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/SnapshotProcessor.java
Add logs when the table snapshot is taken and when emitting a kafka message for a single record/mutation
=> DBZ-2066 Add more logs

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/SnapshotProcessor.java
https://issues.redhat.com/browse/DBZ-2117
Cassandra Connector cannot capture delete events when TTL passes for collection-type column at this moment because of the restriction in Cassandra. 
To avoid the errors encountered during snapshot for collection-type columns:
- Do not call ttl() on collection-type columns during snapshot.
- Do not call write_time() on any columns during snapshot, use `execution_time` instead of `write_time` for `source.ts_ms` for snapshot events.
=> [DBZ-2117] Fix ttl() and write_time() error for collection-type column during snapshot

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/BlackHoleCommitLogTransfer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogProcessor.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogTransfer.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/CassandraConnectorConfigTest.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/CommitLogPostProcessorTest.java
- Catch all exceptions when processing commitLogFiles instead of just IOException, if users use their self-implemented CommitLogTransfer class instead of the default BlackHoleCommitLogTransfer, Cassandra Connector doesn't need to stop for commitLog processing errors.
- Enable Cassandra Connector to re-process error commitLogFiles when related config is enabled.
=> [DBZ-2410] Improve error handling for Cassandra Connector

debezium-connector-db2/src/test/docker/db2-cdc-docker/Dockerfile
https://issues.redhat.com/browse/DBZ-2257
=> DBZ-2257 Lock Db2 Dockerfile version to 11.5.0.0a.

README.md, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogProcessor.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogUtil.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/FieldFilterSelector.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/Filters.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/SnapshotProcessor.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/CassandraConnectorConfigTest.java, debezium-connector-cassandra/src/test/resources/cassandra-unit.yaml, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java, debezium-connector-db2/src/test/java/io/debezium/connector/db2/Db2ConnectorIT.java, debezium-connector-db2/src/test/java/io/debezium/connector/db2/SchemaHistoryTopicIT.java, debezium-connector-db2/src/test/java/io/debezium/connector/db2/util/TestHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/AlterTableParserListener.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SchemaHistoryTopicIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/TransactionMetadataIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
* add include/exclude list properties for cassandra, db2 and oracle incubator connectors
* deprecate whitelist/blacklist properties
* clean some code + minor housekeeping
fixes https://issues.redhat.com/browse/DBZ-2462
=> DBZ-2462 avoid divisive languange in incubator connectors

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogReadHandlerImpl.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/DurationTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/InetAddressDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/ListTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/LogicalTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/MapTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/SetTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/TimeUUIDTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/TimestampTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/UUIDTypeDeserializer.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializerTest.java
This PR is to fix the issue in https://issues.redhat.com/browse/DBZ-2512:
After deserializing UUID column from Cassandra, we need convert the deserialized UUID value to String in order to fit in Kafka Connect Schema which doesn't have a UUID type. We need to add the same step to convert each UUID element in deserialized Collection<UUID> column to String as well, otherwise we'll get error when sending out change event to kafka for Collection<UUID> columns.
=> [DBZ-2512]: Fix error with collection type of UUID

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-2607
A regression was introduced by the LogMiner implementation that required `database.schema` to also be used for XStream.  This PR fixes this regression and does not require this configuration option to be provided when using XStreams.
=> DBZ-2607 Fix NullPointerException when getting all table ids

debezium-connector-cassandra/pom.xml
`cassandra-driver-corer` has a dependency of `guava 19.0`, which however is overwritten by `guava 18.0` introduced by `cassandra-all`. This PR forces cassandra connector to use `guava 19.0` instead of `guava 18.0`.
=> [DBZ-2008] Fix Guava Compatibility issue.

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2Connection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-2629
This PR makes a small re-arrangement of SQL commands to avoid the `ALTER SESSION` resulting in an ORA-01013.
=> DBZ-2629 Fix LogMiner stopping due to ORA-01013

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java
https://issues.redhat.com/browse/DBZ-2859
This PR adds a new database.url configuration field that can be used to provide a raw JDBC url. Right now, we are limited by having to specify a hostname when defining the JDBC connection which can be very limiting when the company is using TNS names in their JDBC urls or RAC cluster connection urls. Here are some examples of those JDBC urls:
_"jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=<hostname>)(PORT=<port>))(CONNECT_DATA=(SERVICE_NAME=<servicename>)))"_
or 
_"jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=OFF)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=<hostname1>)(PORT=<port1>))(ADDRESS=(PROTOCOL=TCP)(HOST=<hostname2>)(PORT=<port2>)))(CONNECT_DATA=SERVICE_NAME=<servicename>)(SERVER=DEDICATED)))"_
among others.
I …
=> DBZ-2859 Support TNS Names and full RAC connection strings

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/HistoryRecorder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/NeverHistoryRecorder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/RowMapper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/Scn.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBuffer.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/valueholder/LogMinerDmlEntry.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/valueholder/LogMinerDmlEntryImpl.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/RowMapperTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/ValueHolderTest.java
https://issues.redhat.com/browse/DBZ-2518
This introduces a new domain type `Scn` for the Oracle Logminer implementation.  There are still some changes that could be done here that tie into [DBZ-2457](https://issues.redhat.com/browse/DBZ-2457) that could be paired with this change.
=> DBZ-2518 Implement Scn as a domain type

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-2711
This PR builds atop of PR #230 by not only expecting minimal database level supplemental logging but also adding a check to verify that tables which are monitored by Oracle specify all columns being logged to maintain consistency with old behavior.
=> DBZ-2711 Implement relaxed supplemental logging requirements for Logminer

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/jsqlparser/SimpleDmlParser.java
Very simple fix. SLF4J handles the last argument specially if it is an exception so that will get the stacktrace printed. This helps with exceptions like a NullPointerException as otherwise all we would get is a simple "null".
=> DBZ-2981 Debezium swallows DML exception in certain cases

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperTest.java
This PR fixes a problem that happens when the NEXT_CHANGE# column in the [V$LOG](https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/V-LOG.html#GUID-FCD3B70B-7B98-40D8-98AB-9F6A85E69F57) view is longer than what the Long data type supports in Java which is a signed long whereas the Oracle value is an unsigned long. 
This PR uses BigInteger as an alternative approach to hold such large numbers. Alternatively, we could use the unsigned long support in Java 8 ( Long.parseUnsignedLong). I think that would be much better but I'm not aware of the backwards compatibility policy of this project so leaving that choice up to the team. 
Nevertheless, I believe some additional JIRA and PR work is needed to guarantee there are no other similar issues within the rest of the source code …
=> DBZ-2855: Missing log file error when current SCN is very large

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-3055
=> DBZ-3055 Capture table state when LogMiner session fails

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBuffer.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBufferMetrics.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBufferMetricsMXBean.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/TransactionMetadataIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferMetricsTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferTest.java
https://issues.redhat.com/browse/DBZ-3090
The outstanding question mentioned in the associated issue is whether or not we believe we need to rework the commit handler logic used by the commit-thread executor.  For now, this PR simply addresses making sure that the transaction-end event is emitted when the transaction is committed.
=> DBZ-3090 Fix emitting transaction end event for LogMiner

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/RowMapper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/DmlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/SimpleDmlParser.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/OracleDmlParserTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/RowMapperTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/ValueHolderTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-3009
This PR removes the `database.schema` configuration option and now supports multiple schemas based on the include/exclude lists provided by the common connector configurations.
=> DBZ-3009 Support multiple schemas with Oracle LogMiner

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/RowMapperTest.java
@gunnarmorling This is the PR I discussed on our call today.  This addresses the JAXB test case failure as well as a small NPE that I uncovered with the recent DBZ-3151 changes.
=> 1.5.b1 test fixes

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
https://issues.redhat.com/browse/DBZ-3128
It is valid for Oracle XStreams to emit LCR records with a source database name with a domain, e.g. `ORCLCDB.WORLD`.  This will happen when the database's `GLOBAL_NAME` is configured with the same like value.
=> DBZ-3128 Revert fix for DBZ-2679.

README.md, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SchemaHistoryTopicIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/TransactionMetadataIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java, debezium-connector-oracle/src/test/resources/log4j.properties
https://issues.redhat.com/browse/DBZ-3154
This should be merged in conjunction with https://github.com/debezium/oracle-vagrant-box/pull/18 as the changes in the helper class reflects the various script changes in the vagrant box repository.
=> DBZ-3154 Update test suite to run in CDB & non-CDB modes.
