debezium/debezium-incubator

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTopicSelector.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
@jpechane Should be merged after https://github.com/debezium/debezium/pull/561 is in.
=> DBZ-644 Adjusting Oracle connector to core changes

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTopicSelector.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.jboss.org/browse/DBZ-725
=> DBZ-725 Removing DB name from topic names

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Also using non-Flashback related SELECT for getting current SCN.
https://issues.jboss.org/browse/DBZ-791
@jpechane 2nd part of that change :)
=> DBZ-791 Using "c##xstrm" user in tests (non-admin user);

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
https://issues.jboss.org/browse/DBZ-793
Requires https://github.com/debezium/debezium/pull/570
=> DBZ-793 Using TableFilter consistently

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleChangeEventSourceFactory.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSource.java
Requires https://github.com/debezium/debezium/pull/569
@jpechane Here's the counterpart to the core PR.
=> DBZ-720 Extracting HistorizedRelationalSnapshotChangeEventSource

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleChangeEventSourceFactory.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SnapshotChangeRecordEmitter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/XStreamChangeRecordEmitter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java
https://issues.jboss.org/browse/DBZ-720
@jpechane And here's the snapshotting implementation for Oracle. Based on top of #8, only the last commit is new.
=> DBZ-720 snapshotting

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.jboss.org/browse/DBZ-795
Based on top of #11.
=> DBZ-795 Fixing misleading source info field name

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
@jpechane And here's the Oracle specific part of the interruption change. Also fixed a bug related to skipping snapshotting after a restart. Requires https://github.com/debezium/debezium/pull/576.
=> DBZ-720 Snapshot interruption handling

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
@jpechane Corresponding incubator PR for https://github.com/debezium/debezium/pull/578.
=> DBZ-40 Pulling up some common code to HistorizedRelationalDatabaseSchema

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
Requires https://github.com/debezium/debezium/pull/579
https://issues.jboss.org/browse/DBZ-801
=> DBZ-801 Parameterizing ChangeEventQueue<DataChangeEvent>

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTopicSelector.java
https://issues.jboss.org/browse/DBZ-627
Requires PR https://github.com/debezium/debezium/pull/580
=> DBZ-627 Unifying TopicSelector implementations

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.jboss.org/browse/DBZ-803
Requires https://github.com/debezium/debezium/pull/583
=> DBZ-803 Finalizing snapshot in offsets also for schema-only snapshots

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDdlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
https://issues.jboss.org/browse/DBZ-804
=> DBZ-804 Emit NUMBER columns as Int32/Int64 if precision and scale allow

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.jboss.org/browse/DBZ-815
Requires https://github.com/debezium/debezium/pull/591
=> DBZ-815 Adding test for heartbeat events for Oracle connector

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
https://issues.jboss.org/browse/DBZ-826
=> DBZ-826 Avoid NPE if commit is called before any offset is prepared

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
https://issues.jboss.org/browse/DBZ-818
=> DBZ-818 Adjusting scale of BigDecimal values to column's scale if needed

debezium-connector-sqlserver/pom.xml, pom.xml
https://issues.jboss.org/browse/DBZ-873
=> DBZ-873 Use CU9 version for testing

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
https://issues.jboss.org/browse/DBZ-897
=> DBZ-897 Skip messages redelivered from database after restart

.travis.yml
https://issues.jboss.org/browse/DBZ-817
=> DBZ-817 Enable Travis builds

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleChangeEventSourceFactory.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeEventSourceFactory.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
Depends on https://github.com/debezium/debezium/pull/665
=> DBZ-776 Support for metrics

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/ChangeTable.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/Lsn.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSchemaChangeEventEmitter.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java, pom.xml
https://issues.jboss.org/browse/DBZ-812
depends on https://github.com/debezium/debezium/pull/651
=> DBZ-812 SqlServer schema changes

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
https://issues.jboss.org/browse/DBZ-1002
=> DBZ-1002 Avoiding NPEs when connector failed to start

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, pom.xml
https://issues.jboss.org/browse/DBZ-1003
Depends on https://github.com/debezium/debezium/pull/694
=> DBZ-1003 Initialize database history

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
https://issues.jboss.org/browse/DBZ-1007
=> DBZ-1007 Log captured but not whitelisted table

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
https://issues.jboss.org/browse/DBZ-1023
=> DBZ-1023 Excluding AUDSYS schema in Oracle

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTaskContext.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerTaskContext.java
Requires https://github.com/debezium/debezium/pull/704
=> DBZ-978 Added last event and captured tables metrics

debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
Needs https://github.com/debezium/debezium/pull/606
=> DBZ-859 Heartbeat is sent after snapshot

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
https://issues.jboss.org/browse/DBZ-1047
=> DBZ-1047 Log proper change tables

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceInfo.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerOffsetContext.java
This is achieved by adding custom toString() to SqlServerOffsetContext
and SourceInfo.
=> DBZ-1066 Improve "Found previous offset" log

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/CaseSensitivenessIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
https://issues.jboss.org/browse/DBZ-1051
=> DBZ-1051 Handle object and db name letter case

debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java, debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerDatabaseSchema.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java, debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/SourceRecordAssert.java
https://issues.jboss.org/browse/DBZ-1067
=> DBZ-1067 Add column blacklisting in SQL Server connector

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
Solve the problem of NullPointerException when there are multiple schema
=> DBZ-1166 NullPointerException When there are multiple tables in different schemas in the whitelist

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSource.java
https://issues.jboss.org/browse/DBZ-1170
=> DBZ-1170 Detect and handle errors like CNFE

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Related to https://github.com/debezium/debezium/pull/809
=> DBZ-212 Refactored LOGICAL_NAME to Parent Abstract Class

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/LcrPosition.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, pom.xml
https://issues.jboss.org/browse/DBZ-1223
=> DBZ-1223 Use LCR position as the record offset

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java, pom.xml
Depends on https://github.com/debezium/debezium/pull/886
=> DBZ-1235 Oracle converted to use source info maker

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
https://issues.jboss.org/browse/DBZ-1283
@jpechane, should go into Alpha2, too.
=> DBZ-1283 Ensuring DB history topic name and server name don't conflict

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, pom.xml
https://issues.jboss.org/browse/DBZ-835
=> DBZ-835 Test for no tombstone

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
@jpechane A small left-over. Technically, the issue has already been resolved in Beta1, but I think it's ok to add this one here without a new issue.
=> DBZ-1317 Removing redundant method

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/Module.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTaskContext.java
https://issues.jboss.org/browse/DBZ-1356
=> DBZ-1356 Metrics for schema history

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, pom.xml
Depends on https://github.com/debezium/debezium/pull/990
=> DBZ-777 Snapshot event metadata set in common snapshot source

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
https://issues.jboss.org/browse/DBZ-1044
=> DBZ-1044 Sanitize column/topic names to always be valid AVRO names

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
@jpechane This needs merging for the release, too.
=> DBZ-1497, DBZ-1015

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/BlockingEventQueue.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTask.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTaskHealthCheck.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraTopicSelector.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CellData.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogPostProcessor.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogProcessor.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogReadHandlerImpl.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogUtil.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/FieldFilterSelector.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/FileOffsetWriter.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/KafkaRecordEmitter.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/SnapshotProcessor.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/network/SslContextFactory.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/CommitLogProcessorTest.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/utils/CommitLogUtilTest.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/AlterTableParserListener.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/BaseParserListener.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/CreateTableParserListener.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
https://issues.jboss.org/browse/DBZ-1391
=> DBZ-1391 Do not allow code after closing brace

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/AlterTableParserListener.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/CreateTableParserListener.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
This PR addresses quite a number of changes that are tightly coupled and which are based on changes to the parent Debezium project in PR https://github.com/debezium/debezium/pull/1033.
~~https://issues.jboss.org/browse/DBZ-1391~~ (applied separately in PR #111)
https://issues.jboss.org/browse/DBZ-1355
=> Parent POM Updates | Checkstyle fixes

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java
https://issues.jboss.org/browse/DBZ-1569
=> DBZ-1569 Test inaccessible no-PK table

.travis.yml
https://issues.jboss.org/browse/DBZ-1605
Depends on https://github.com/debezium/debezium/pull/1127
=> DBZ-1605 Use formatter rules from Maven module

.travis.yml
https://issues.jboss.org/browse/DBZ-1603
=> DBZ-1603 Only run format validation on Travis CI and not auto-format.

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
https://issues.jboss.org/browse/DBZ-825
=> DBZ-825 Unify decimal upscaling

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java
https://issues.redhat.com/browse/DBZ-1552
=> DBZ-1552 Support for decimal mode in Oracle config

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/TransactionMetadataIT.java
https://issues.redhat.com/browse/DBZ-1052
Depends on https://github.com/debezium/debezium/pull/1221
=> DBZ-1052 Transaction metadata for Oracle

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2Connection.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2StreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-1794
=> DBZ-1794 Remove Microsoft references in Db2 connector comments

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
https://issues.redhat.com/browse/DBZ-1760
Depends on https://github.com/debezium/debezium/pull/1271
=> DBZ-1760 Allow skipping of invalid events

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2DatabaseSchema.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
https://issues.redhat.com/browse/DBZ-1134
=> DBZ-1134 Passing converter registry for Db2 and Oracle

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-1726
This accompanies PR https://github.com/debezium/debezium/pull/1316 and should be applied after the main repository's PR has been merged.
=> DBZ-1726 RelationalSnapshotChangeEventSource API changes

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
https://issues.redhat.com/browse/DBZ-1723
@jpechane, that accompanies https://github.com/debezium/debezium/pull/1304 and should be merged after that one.
=> DBZ-1723 Adjusting to changes in BaseSourceTask

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
https://issues.redhat.com/browse/DBZ-1863
Requires https://github.com/debezium/debezium/pull/1329
=> DBZ-1863 Centralizing coordinator shutdown

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogProcessor.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogReadHandlerImpl.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/RecordMaker.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/SnapshotProcessor.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/SourceInfo.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/FileOffsetWriterTest.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/QueueProcessorTest.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/SnapshotProcessorTest.java
Follow up on https://github.com/debezium/debezium-incubator/pull/149
=> DBZ-1892 Fix sourceInfo bug

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraTopicSelector.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/KafkaRecordEmitter.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/KeyspaceTable.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/QueueProcessor.java
Replace custom CassandraTopicSelector with Debezium TopicSelector.
=> [DBZ-1407] Use Debezium TopicSelector

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
Minor changes needed for `ChangeEventSourceCoordinator` signature change.
=> DBZ-1859 Enhance MongoDB connector metrics

README.md, debezium-connector-oracle/pom.xml, pom.xml
https://issues.redhat.com/browse/DBZ-1878
=> DBZ-1878 Use Oracle driver from central

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorTask.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2SchemaChangeEventEmitter.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2SnapshotChangeEventSource.java, debezium-connector-db2/src/test/java/io/debezium/connector/db2/SchemaHistoryTopicIT.java, debezium-connector-db2/src/test/java/io/debezium/connector/db2/util/TestHelper.java, debezium-connector-oracle/pom.xml, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java, pom.xml
https://issues.redhat.com/browse/DBZ-1904
=> DBZ-1904 Schema history topic support

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, debezium-connector-db2/src/test/java/io/debezium/connector/db2/Db2ConnectorIT.java
https://issues.redhat.com/browse/DBZ-2051
=> DBZ-2051 Replace initial_schema_only with schema_only

debezium-connector-cassandra/pom.xml, debezium-connector-db2/pom.xml, debezium-connector-oracle/pom.xml
https://github.com/debezium/debezium/pull/1507
=> DBZ-2088 Use POSIX tar

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SchemaHistoryTopicIT.java, pom.xml
https://issues.redhat.com/browse/DBZ-2056
=> DBZ-2056 Test for schema topic

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CassandraConnectorContext.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CellData.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/converter/UserTypeConverter.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/EmbeddedCassandraConnectorTestBase.java, debezium-connector-cassandra/src/test/java/io/debezium/connector/cassandra/transforms/CassandraTypeConverterTest.java
The PR fixes the following issues:
- Fails to convert UDT type schema.
- Casandra Connection is not closed when connector context fails to be initialized.
=> [DBZ-2091] Fix errors encountered for User-Defined-Type data

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SchemaHistoryTopicIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/StreamingDatatypesIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/TransactionMetadataIT.java
https://issues.redhat.com/browse/DBZ-1312
=> DBZ-1312 Change whitelist format to schema.table ids

debezium-connector-db2/pom.xml, debezium-connector-db2/src/test/java/io/debezium/connector/db2/Db2ConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-775
While this PR addresses adding missing tests to DB2 and Oracle connectors, there is a parallel PR in the main code repository to accompany documentation updates that should be merged in tandem.
=> DBZ-775 Add tests for column masking/truncation and message key columns

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ValueConverters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
https://issues.redhat.com/browse/DBZ-1814
For incubator repository compilation failures after introduction of DBZ-1814 with main repository.
=> DBZ-1814 Fix compilation failures

debezium-connector-db2/src/test/java/io/debezium/connector/db2/Db2ConnectorIT.java, debezium-connector-db2/src/test/java/io/debezium/connector/db2/util/TestHelper.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-1916
=> DBZ-1916 Add tests for datatype.propagate.source.type

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CellData.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/CassandraTypeKafkaSchemaBuilders.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/ListTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/MapTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/SetTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/TupleTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/UserTypeDeserializer.java
Final fix for issue described in https://issues.redhat.com/browse/DBZ-2103 by making all column type optional consistently.
=> [DBZ-2103] Ultimate fix for data mismatch error.

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogReadHandlerImpl.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/CollectionTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/ListTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/MapTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/SetTypeDeserializer.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/TypeDeserializer.java
Fix the error reported in https://issues.redhat.com/browse/DBZ-2345
=> [DBZ-2345] Fix error encountered when processing commitLogs related to collection-type columns.

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/CollectionTypeDeserializer.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2Connection.java
https://issues.redhat.com/browse/DBZ-1491
=> DBZ-1491 Changes required after core refactoring

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-2452
=> DBZ-2452 Allow snapshotting tables/schemas with hyphens

debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2Connection.java, debezium-connector-db2/src/main/java/io/debezium/connector/db2/Db2ConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, pom.xml
https://issues.redhat.com/projects/DBZ/issues/DBZ-2423
Follow-up to https://github.com/debezium/debezium/pull/1752
@rk3rn3r Ready for review
=> DBZ-2423 Support default port in JDBC driver

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogReadHandlerImpl.java
https://issues.redhat.com/browse/DBZ-2498
=> [DBZ-2498]: Fix error with frozen collection type column

debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/CommitLogReadHandlerImpl.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/KafkaRecordEmitter.java, debezium-connector-cassandra/src/main/java/io/debezium/connector/cassandra/SnapshotProcessor.java
Replicate https://github.com/debezium/debezium-incubator/pull/191
=> [DBZ-2510] Add more logs.

.travis.yml, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/jsqlparser/SimpleDmlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-2531
NOTE:
While this PR is independent of PR #195, I found that LogMiner has the potential to fail to lookup a table's schema due to incorrect handling of the table-name case.  Therefore its possible when testing this PR against LogMiner specifically, a single test will fail.  By incorporating the changes from PR #195, both connection adapters pass.
=> DBZ-2531 Implement connection retry for Oracle

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/RowMapper.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/RowMapperTest.java
https://issues.redhat.com/browse/DBZ-2555
=> DBZ-2555 Fix LogMiner schema change event dispatch

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, pom.xml
https://issues.redhat.com/browse/DBZ-2607
=> DBZ-2607 Query param must not be in string

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-2683
I've taken PR #205 and pulled it into a separate PR with the unit test.  I did this because the original PR was opened against the contributor's master branch rather than a topic branch and didn't feel comfortable pushing the unit test to their fork that way.
=> DBZ-2683 Add support for partitioned tables

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
https://issues.redhat.com/browse/DBZ-2679
=> DBZ-2679 Handle LCR events with database names with domains

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-1446
=> DBZ-1446 Avoid Oracle "no snapshot found based on specified time" during snapshot

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
https://issues.redhat.com/browse/DBZ-2763
=> DBZ-2763 LogMiner history retention disabled by default

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
https://issues.redhat.com/browse/DBZ-2759
=> DBZ-2759 Capture all commit and rollback redo entries

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-2801
=> DBZ-2801 Only require database.out.server.name for XStreams

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-2797
Once tests have passed locally, I'll convert this to a formal pull request.
=> DBZ-2797 Remove explicitly hardcoded tablespaces

debezium-connector-oracle/pom.xml, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/OracleDmlParserTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-2856
=> DBZ-2856 Fix passing connection adapter to Surefire tests

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-2849
=> DBZ-2849 Fix value conversion with non-compliant Avro column names

debezium-connector-oracle/pom.xml
https://issues.redhat.com/browse/DBZ-2890
=> DBZ-2890 Remove SLF4J from Oracle distro

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-2825
=> DBZ-2825 Fix archive log support for Oracle LogMiner

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/OracleChangeRecordValueConverter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/OracleDmlParserTest.java, debezium-connector-oracle/src/test/resources/ddl/create_table.sql
https://issues.redhat.com/browse/DBZ-2784
This PR is based on the work in PR #226, so it should be merged only after that has been merged.
=> DBZ-2784 Support DATE column types with Oracle Logminer

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-2920
=> DBZ-2920 Fix Logminer DML operations using continuation

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-2949
=> DBZ-2949 Guard against LAST_DDL_TIME with value of 0

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java
Adding extra logs to make explicit the type of DML operations
=> DBZ-2980 Additional logging for number and type of sql operations

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/OracleChangeRecordValueConverter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/OracleDmlParserTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/ValueHolderTest.java
https://issues.redhat.com/browse/DBZ-2733
=> DBZ-2733 Fix DecimalMode for Oracle Logminer

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-2891
=> DBZ-2891 Set watermark in the XStream thread

README.md
https://issues.redhat.com/browse/DBZ-2901
=> DBZ-2901 Update README for building Debezium locally before running non-core repos

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
https://issues.redhat.com/browse/DBZ-2420
=> DBZ-2420 Use database configs from RelationalDatabaseConnectorConfig

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/UpdateParserListener.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/jsqlparser/SimpleDmlParser.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/HistoryRecorder.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerMetricsMXBean.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/OracleChangeRecordValueConverter.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/RowMapper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBufferMetricsMXBean.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/valueholder/LogMinerDmlEntry.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/valueholder/LogMinerDmlEntryImpl.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-2999
=> DBZ-2999 Improve Logminer logging

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
https://issues.redhat.com/browse/DBZ-2939
=> DBZ-2939 Added ORA-01333 as valid retriable exception

debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/RequireDatabaseOption.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipTestDependingOnDatabaseOptionRule.java
https://issues.redhat.com/browse/DBZ-3110
=> DBZ-3110 Introduce RequireDatabaseOption test annotation

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseVersion.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-3001
This is an initial pass at providing a MAX SCN calculation based on the Oracle database version.  We've seeded the MAX values returned based on data gathered either through my testing of Oracle 12.2 and 19.3 as well user input for Oracle 19.6.
@ant0nk @mpermar if either of you can pull down this PR into your local branch and test it, I would be most grateful.
=> DBZ-3001 Control MAX Scn for LogMiner based on Oracle version

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
https://issues.redhat.com/browse/DBZ-3153
=> DBZ-3153 Capture LogMiner parameters when LogMiner session fails to start

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-3109
=> DBZ-3109 Account for multiple log group types

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
https://issues.redhat.com/browse/DBZ-3151
This PR depends on https://github.com/debezium/debezium/pull/2150.
=> DBZ-3151 Properly handle system-generated hidden column unique indexes

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/RowMapper.java
https://issues.redhat.com/browse/DBZ-3165
=> DBZ-3165 Remove dependency on JAXB

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnector.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/TransactionalBufferTest.java
https://issues.redhat.com/browse/DBZ-3119
=> DBZ-3119 Implement Config validation

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
https://issues.redhat.com/browse/DBZ-3172
=> DBZ-3172 Convert NUMBER to boolean

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorFilterIT.java
https://issues.redhat.com/browse/DBZ-3167
=> DBZ-3167 Removed column.blacklist, cleaned up config definition

debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/EndToEndPerf.java, debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/parser/LogMinerDmlParserPerf.java
@jpechane This is the small fixes to get the benchmark module to compile.
Sorry for missing these.
=> Fix Benchmark for 1.5.0.Beta1

debezium-microbenchmark-oracle/pom.xml, pom.xml
Fix build to work with release plugin
=> [release] Fix dependencies for release plugin

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
https://issues.redhat.com/browse/DBZ-2875
=> DBZ-2875 Start streaming LogMiner changes after offset SCN

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerMetrics.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerMetricsMXBean.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-3038
=> DBZ-3038 Capture additional LogMiner JMX metrics

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
https://issues.redhat.com/browse/DBZ-3193
=> DBZ-3193 Fix IndexOutOfBoundsException with "IS NULL" predicate

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/TransactionalBufferMetrics.java
https://issues.redhat.com/browse/DBZ-3200
=> DBZ-3200 Fix potential division-by-zero with CommitThroughput metric

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
https://issues.redhat.com/browse/DBZ-3194
=> DBZ-3194 Allow ORA-01284 errors to be retried

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-3036
=> DBZ-3036 Detect and skip Oracle IOT special tables

debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java, debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/converters/NumberOneToBooleanConverter.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleNumberOneIT.java, debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/OracleDmlParserTest.java
https://issues.redhat.com/browse/DBZ-3208
* NUMBER(1) column types emit as numeric
* Added OOTB converter, NumberOneToBooleanConverter
=> DBZ-3208 Don't emit NUMBER(1) as boolean types
